spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/spring-boot-tutorial-prod'
    username: postgres
    password: 04012003fec
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update